server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com   #eureka服务端的实例名称
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己
    fetch-registry: false   #false表示自己端就是注册中心
    service-url:
      #defaultZone: http://eureka7002.com:7002/eureka/  #集群指向其他eureka
      defaultZone: http://eureka7001.com:7001/eureka/  #单机
 # server:
  #  enable-self-preservation: false #关闭自我保护
   # eviction-interval-timer-in-ms: 2000